### ISSUE TITLE
RepEx on Bridges

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.repex#20]
Since experiments are running and stable for now on Stampede 2, we should be focusing on moving RepEx back to Bridges (since the original repex allocation for the science workloads is on Bridges).
 
I am working with the Bridges staff to help resolve the earlier issue faced regarding command line I/O redirection. However, we seem t have run into an issue on the RP end. Attempting to run RepEx on Bridges yields the following error in the MD tasks:

```[mpiexec@r002.pvt.bridges.psc.edu] check_exit_codes (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:114): unable to run proxy on r002.pvt.bridges.psc.edu (pid 11906)
[mpiexec@r002.pvt.bridges.psc.edu] poll_for_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:152): check exit codes error
[mpiexec@r002.pvt.bridges.psc.edu] HYD_dmx_poll_wait_for_proxy_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:205): poll for event error
[mpiexec@r002.pvt.bridges.psc.edu] HYD_bstrap_setup (../../../../../src/pm/i_hydra/libhydra/bstrap/src/intel/i_hydra_bstrap.c:731): error waiting for event
[mpiexec@r002.pvt.bridges.psc.edu] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1919): error setting up the boostrap proxies

```

This error appears in the STDERR file of the MD tasks. 
The sandbox has been opened, and I will send the path via slack.

Thanks

**Comment by SrinivasMushnoori** [comment]
[Uploading re.session.McEwan.scm177.018371.0000.zip…](Updating ticket wit sandbox)

**Comment by andre-merzky** [comment]
Hmm, I may be missing something, but the tasks in that sandbox are still loading the intel module?  I you can, please attach a `STDERR` file for one of the tasks in a session where that module is not loaded, or paste it here.  Thanks!

@iparask :  Can you have a look at this ticket, please, if you have the time?  What happens is the following:
RP loads the gcc module as we need that for mpirun to work.  The task loads the intel module because it depends on that.  mpirun now fails because the gcc module module gets swapped out before mpirun is called.
We basically need a launch method which does not need to load gcc.  If we don't find that, we need to wrap the application task into a shell script which loads the intel module *after* mpirun placed it onto the compute node.

Either way, this points at another env violation which we need to consider.

**Comment by SrinivasMushnoori** [comment]
Let me check.

**Comment by iparask** [comment]
@andre-merzky, 
if you check `rep.0002.0000.md` STDERR you will see:
```
[mpiexec@r002.pvt.bridges.psc.edu] check_exit_codes (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:114): unable to run proxy on r002.pvt.bridges.psc.edu (pid 11733)
[mpiexec@r002.pvt.bridges.psc.edu] poll_for_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:152): check exit codes error
[mpiexec@r002.pvt.bridges.psc.edu] HYD_dmx_poll_wait_for_proxy_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:205): poll for event error
[mpiexec@r002.pvt.bridges.psc.edu] HYD_bstrap_setup (../../../../../src/pm/i_hydra/libhydra/bstrap/src/intel/i_hydra_bstrap.c:731): error waiting for event
[mpiexec@r002.pvt.bridges.psc.edu] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1919): error setting up the boostrap proxies
```
Let's move this discussion on RP. I think this is similar to radical-cybertools/radical.pilot#2128.
